### ISSUE TITLE
cannot start task from azure pipeline

### ISSUE THREAD

**Issue by elnmgoo** [duglah/azuredevops-arduino-cli-task#1]
Hi 

I've installed the 'arduino-cli' from marketplace in azure pipelines, and added the azure-pipelines.yml in my repostory (liike the example at your github).
I keep get the error  "A task is missing. The pipeline references a task called 'ArduinoCliInstall' with version '0'. This indicates that the specific task version can not be found. (job 'Job', step ''.)"
The error point to the following line in th eyml file: "- task: ArduinoCliInstall@0"

Best regards,
Mario

**Comment by pmanstein** [comment]
Hey Mario,

looks like the extension isn't installed to your organization.
Could you please check if the extension is installed here: https://dev.azure.com/{YOUR_ORGANIZATION}/_settings/extensions?tab=installed
Or use: https://dev.azure.com/ (login to your organization) > Organization Settings (bottom left) > Extensions

Then edit your azure-pipelines.yml in the portal and search for the arduino-cli tasks in the tasks menu on the right to verify you can access the tasks.

**Comment by elnmgoo** [comment]
Hi Philipp,

Thank you for your quick response.
The extension is installed on my system, but after some testing I noticed
that I had to change the major version of the task ArduinoCliInstall  to 1
(instead of 0):

- task: ArduinoCliInstall@1
  inputs:
    version: 'latest'

After that everything seems to work just fine.

Best regards,

Mario



Op ma 25 mei 2020 om 09:55 schreef Philipp Manstein <
notifications@github.com>:

**Comment by pmanstein** [comment]
Hey Mario,

I'm glad this works now.
So i've to update the documentation and examples.
